This File exists to be the main file for my work

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import psycopg2
import getpass

from dotenv import load_dotenv
from configparser import ConfigParser
from sqlalchemy import create_engine

import os

In [17]:
# We seek to use a config file to avoid absolute file paths
file = 'config.ini' #config file of interest

config = ConfigParser()
config.read(file)

print(config.sections()) # outlines the sections in the file

['paths', 'postgres']

In [18]:
# accesses the motor data element, in this case it's the file path for it
paths = [config['paths']['motor_data'], config['paths']['claims_data']]

#path
df_motor = pd.read_csv(paths[0], sep=";")
df_claims = pd.read_csv(paths[1], sep=";")

In [19]:
df_motor.columns.tolist(), df_claims.columns.tolist() # It's important to understand the columns that exist in the tables

(['ID',
  'Date_start_contract',
  'Date_last_renewal',
  'Date_next_renewal',
  'Date_birth',
  'Date_driving_licence',
  'Distribution_channel',
  'Seniority',
  'Policies_in_force',
  'Max_policies',
  'Max_products',
  'Lapse',
  'Date_lapse',
  'Payment',
  'Premium',
  'Cost_claims_year',
  'N_claims_year',
  'N_claims_history',
  'R_Claims_history',
  'Type_risk',
  'Area',
  'Second_driver',
  'Year_matriculation',
  'Power',
  'Cylinder_capacity',
  'Value_vehicle',
  'N_doors',
  'Type_fuel',
  'Length',
  'Weight'],
 ['ID', 'Cost_claims_year', 'Cost_claims_by_type', 'Claims_type'])

In [20]:
df_motor

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Area,Second_driver,Year_matriculation,Power,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.00,0,P,NaN,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105550,53498,30/07/2018,30/07/2018,30/07/2019,25/07/1981,14/02/2007,0,1,1,1,...,0,0,2000,110,1997,24320.00,5,D,4.740,1480
105551,53499,16/08/2018,16/08/2018,16/08/2019,08/12/1976,29/11/2017,0,1,1,1,...,0,0,2013,129,1998,30861.97,5,P,4.650,1440
105552,53500,21/11/2018,21/11/2018,21/11/2019,01/04/1974,05/10/2011,0,1,1,1,...,0,0,1999,55,999,7800.00,5,P,3.495,830
105553,53501,21/11/2018,21/11/2018,21/11/2019,15/09/1946,02/02/1982,0,1,1,1,...,0,0,2004,90,1753,16610.00,5,D,4.555,1399
105554,53502,01/10/2018,01/10/2018,01/10/2019,09/05/1973,30/09/1991,1,1,1,1,...,0,0,2010,140,1968,33400.00,5,D,4.854,1699

In [48]:
df_motor['Date_last_renewal'] = pd.to_datetime(df_motor['Date_last_renewal'], format='%d/%m%Y')

In [49]:
df_motor['Date_last_renewal']

0        2015-11-05
1        2016-11-05
2        2017-11-05
3        2018-11-05
4        2017-09-26
            ...
105550   2018-07-30
105551   2018-08-16
105552   2018-11-21
105553   2018-11-21
105554   2018-10-01
Name: Date_last_renewal, Length: 105555, dtype: datetime64[ns]

In [21]:
df_claims.head()

   ID  Cost_claims_year  Cost_claims_by_type        Claims_type
0  28            332.02               332.02          complaint
1  36             57.35                57.35  travel assistance
2  42             57.50                57.50  travel assistance
3  60            138.90                67.25  travel assistance
4  60            138.90                71.65  travel assistance

#### Now that we have the data set of interest, it's useful for us to outline the questions of interest.

- Who claims?
    - What is there demographic?

- How much do they cost?

- What variables drive risk?

- What should the insurer charge?

To answer these questions it would be important that we correctly format and clean the data.

In [22]:
#df_motor.dropna(subset=['Length','Date_lapse'])
df_motor.isna().sum() # checks the number of  Na values in the columns

ID                          0
Date_start_contract         0
Date_last_renewal           0
Date_next_renewal           0
Date_birth                  0
Date_driving_licence        0
Distribution_channel        0
Seniority                   0
Policies_in_force           0
Max_policies                0
Max_products                0
Lapse                       0
Date_lapse              70408
Payment                     0
Premium                     0
Cost_claims_year            0
N_claims_year               0
N_claims_history            0
R_Claims_history            0
Type_risk                   0
Area                        0
Second_driver               0
Year_matriculation          0
Power                       0
Cylinder_capacity           0
Value_vehicle               0
N_doors                     0
Type_fuel                1764
Length                  10329
Weight                      0
dtype: int64

In [23]:
# checks if the three columns found previously are actually the only columns on interest in this regard.
df_motor.isnull().any()
df_motor_nulls = df_motor.loc[:, df_motor.isnull().any()]
print(df_motor_nulls)

       Date_lapse Type_fuel  Length
0             NaN         P     NaN
1             NaN         P     NaN
2             NaN         P     NaN
3             NaN         P     NaN
4             NaN         P     NaN
...           ...       ...     ...
105550        NaN         D   4.740
105551        NaN         P   4.650
105552        NaN         P   3.495
105553        NaN         D   4.555
105554        NaN         D   4.854

[105555 rows x 3 columns]

In [24]:
df_motor.info(memory_usage = 'Deep') # can use True instead if the calculation is too computationally intensitive

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105555 entries, 0 to 105554
Data columns (total 30 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    105555 non-null  int64
 1   Date_start_contract   105555 non-null  object
 2   Date_last_renewal     105555 non-null  object
 3   Date_next_renewal     105555 non-null  object
 4   Date_birth            105555 non-null  object
 5   Date_driving_licence  105555 non-null  object
 6   Distribution_channel  105555 non-null  int64
 7   Seniority             105555 non-null  int64
 8   Policies_in_force     105555 non-null  int64
 9   Max_policies          105555 non-null  int64
 10  Max_products          105555 non-null  int64
 11  Lapse                 105555 non-null  int64
 12  Date_lapse            35147 non-null   object
 13  Payment               105555 non-null  int64
 14  Premium               105555 non-null  float64
 15  Cost_claims_year      105555 non-null  float64
 16  N_claims_year         105555 non-null  int64
 17  N_claims_history      105555 non-null  int64
 18  R_Claims_history      105555 non-null  float64
 19  Type_risk             105555 non-null  int64
 20  Area                  105555 non-null  int64
 21  Second_driver         105555 non-null  int64
 22  Year_matriculation    105555 non-null  int64
 23  Power                 105555 non-null  int64
 24  Cylinder_capacity     105555 non-null  int64
 25  Value_vehicle         105555 non-null  float64
 26  N_doors               105555 non-null  int64
 27  Type_fuel             103791 non-null  object
 28  Length                95226 non-null   float64
 29  Weight                105555 non-null  int64
dtypes: float64(5), int64(18), object(7)
memory usage: 24.2+ MB

In [25]:
df_claims.info() # from this we can say that the claims dataframe doesn't need missing values handling.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7366 entries, 0 to 7365
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   7366 non-null   int64
 1   Cost_claims_year     7366 non-null   float64
 2   Cost_claims_by_type  7366 non-null   float64
 3   Claims_type          7366 non-null   object
dtypes: float64(2), int64(1), object(1)
memory usage: 230.3+ KB

Now a key detail to understand is that there's two main ways to handle missing values, either removal of the data point of issue or the substitution of those said data points. (1)[Kwak, S. G., & Kim, J. H. (2017). Statistical data preparation: management of missing values and outliers. Korean Journal of Anesthesiology, 70(4), 407–411. https://doi.org/10.4097/kjae.2017.70.4.407.]

To know which to perform it is important to quantify the statistical significance of removing the offending data points. A good way of checking this is finding if there's a pattern within the missingness or if the missingness is simply random. 

To properly check this we will be using Little’s MCAR test. After which specific trends of interest could be extracted using further statistical methods.

#### Algorithm Behind Little’s MCAR Test

- Group Data by Missingness Patterns: The dataset is divided into groups based on missing data patterns (e.g., one group where variable X is missing, another where Y is missing, etc.).

- Calculate Means and Covariances for Each Group: Compute the mean vectors and covariance matrices for each missing data group.

- Estimate Expected Mean Differences: Using maximum likelihood estimation (MLE), the test estimates the expected mean for each variable based on available data.

- Compute the Test Statistic: The test calculates a Chi-Square statistic by comparing the estimated means across missing data patterns.

- Compare with the Chi-Square Distribution: The calculated Chi-Square value is compared with a theoretical Chi-Square distribution to determine significance (p-value).

#### Decision Rule:

- p > 0.05 → Fail to reject the null hypothesis → Data is MCAR (missing completely at random).

- p ≤ 0.05 → Reject the null hypothesis → Data is MAR or MNAR, meaning missingness follows a pattern.

In [26]:
#df_length_fuel_lapse = df_motor[['ID', 'Length', 'Type_fuel', 'Date_lapse']].isna()
#df_length_fuel_lapse.value_counts()

missing = df_motor[['Length', 'Type_fuel', 'Date_lapse']].isna().any(axis=1)

result = df_motor.loc[missing, ['ID', 'Length', 'Type_fuel', 'Date_lapse']]

unique_result = result.drop_duplicates('ID')

len(unique_result)/len(df_motor) * 100

33.31533323859599

With 33.32% missingness, it is very unlikely that the data can simply be drop as the impact will be significant.

Due to this we will use machine learning classification to perform this fix.

In [28]:
#df_motor['Date_lapse'] = pd.to_datetime(df_motor['Date_lapse']) , # doesn't work rn due to Nan values

In [29]:
train = df_motor[df_motor[['Length', 'Type_fuel', 'Date_lapse']].notna()]
train[['Length', 'Type_fuel', 'Date_lapse']]

        Length Type_fuel Date_lapse
0          NaN         P        NaN
1          NaN         P        NaN
2          NaN         P        NaN
3          NaN         P        NaN
4          NaN         P        NaN
...        ...       ...        ...
105550   4.740         D        NaN
105551   4.650         P        NaN
105552   3.495         P        NaN
105553   4.555         D        NaN
105554   4.854         D        NaN

[105555 rows x 3 columns]

In [50]:
df_motor['Type_fuel'].unique()

array(['P', 'D', nan], dtype=object)

In [27]:
df_motor.columns # we inspect the columns here to find the potential features of interest

Index(['ID', 'Date_start_contract', 'Date_last_renewal', 'Date_next_renewal',
       'Date_birth', 'Date_driving_licence', 'Distribution_channel',
       'Seniority', 'Policies_in_force', 'Max_policies', 'Max_products',
       'Lapse', 'Date_lapse', 'Payment', 'Premium', 'Cost_claims_year',
       'N_claims_year', 'N_claims_history', 'R_Claims_history', 'Type_risk',
       'Area', 'Second_driver', 'Year_matriculation', 'Power',
       'Cylinder_capacity', 'Value_vehicle', 'N_doors', 'Type_fuel', 'Length',
       'Weight'],
      dtype='object')

In [40]:
df_motor[['Date_birth']].mean()

TypeError: Could not convert ['15/04/195615/04/195615/04/195615/04/195615/04/195615/04/195618/03/197518/03/197518/03/197518/03/197510/07/197310/07/197310/07/197310/07/197310/07/197321/10/196621/10/196621/10/196614/05/194611/05/194111/05/194111/05/194122/10/194922/10/194922/10/194922/10/194922/10/194922/10/194904/06/194604/06/194604/06/194616/02/195116/02/195116/02/195123/06/195123/06/195123/06/195105/09/194505/09/194505/09/194504/11/195404/11/195404/11/195401/01/195801/01/195801/01/195809/09/194109/09/194109/09/194106/01/194320/07/194420/07/194404/05/194304/05/194304/05/194301/04/194401/04/194401/04/194413/04/195913/04/195931/05/196015/10/194609/08/196109/08/196112/08/196113/01/196113/01/196113/01/196118/08/196418/08/196401/04/194101/04/194101/04/194101/04/194101/04/194101/04/194103/01/198203/01/198208/05/195108/05/195108/05/195131/07/195319/09/198519/09/198505/09/195816/10/195816/10/195819/10/196119/10/196119/10/196101/01/194401/01/194403/06/194003/06/194003/06/194022/07/195822/07/195802/05/196302/05/196326/04/196422/02/196522/02/196522/02/196502/08/196702/08/196702/08/196702/08/196707/05/196601/12/196901/12/196901/12/196919/02/197119/02/197119/02/197108/09/194011/06/194311/06/194311/06/194314/05/194315/01/194515/01/194515/05/194916/09/195216/09/195216/09/195216/09/195217/08/195501/06/195730/08/195530/08/195515/08/195915/08/195915/08/195915/08/195915/08/195915/08/195915/08/195915/08/195908/04/195908/04/195927/12/195927/12/195920/04/196017/10/195917/10/195917/10/195917/10/195931/07/196031/07/196031/07/196002/03/196302/03/196302/03/196313/12/196013/12/196013/11/194113/11/194113/11/194126/11/197926/11/197909/06/195109/06/195109/06/195115/01/197115/01/197111/01/197215/11/198501/04/194015/01/197915/01/197915/01/197911/07/194410/02/195226/06/195314/07/195414/07/195414/07/195402/03/195602/03/195605/03/195506/09/194506/09/194515/05/195115/05/195115/05/195115/05/195126/10/195926/10/195926/10/195905/10/194606/06/194706/06/194706/06/194707/10/195707/10/195707/10/195716/06/196516/06/196516/06/196507/08/196419/05/196805/12/197005/12/197005/12/197007/07/195720/10/195803/10/197503/10/197503/10/197501/02/194701/02/194717/06/195505/03/196705/03/196705/03/196705/03/196701/04/194616/09/194916/09/194920/09/194820/09/194819/10/194919/10/194919/10/194919/06/195119/06/195115/10/194215/10/194221/01/194321/01/194320/08/194820/08/194801/03/195601/11/195401/11/195410/06/196408/02/196408/02/196423/05/196523/05/196523/05/196523/05/196503/10/196303/10/196315/01/197405/10/197001/08/197001/08/197001/08/197001/08/197004/07/197106/11/198306/11/198306/11/198309/10/194609/10/194609/10/194604/08/195729/06/195829/06/195829/06/195818/03/196218/03/196218/03/196230/10/197030/10/197030/10/197019/02/197119/02/197130/04/197327/11/198024/07/198218/11/197918/11/197925/03/197413/12/197013/12/197012/06/196512/06/196512/06/196519/03/195519/03/195519/03/195507/09/196707/09/196707/09/196722/05/196622/05/196622/05/196609/06/196601/01/196401/05/196930/03/196905/04/197105/04/197105/04/197131/05/197931/05/197931/05/197910/11/195610/11/195610/11/195623/07/198523/07/198523/07/198523/07/198507/08/197707/08/197707/08/197707/08/197707/08/197710/12/197210/10/195827/03/196027/03/196027/03/196027/06/194027/06/194027/06/194017/01/194023/03/196523/03/196523/03/196524/03/196608/03/196708/03/196708/03/196708/01/197208/01/197208/01/197201/02/197001/02/197010/12/197310/12/197310/12/197312/10/197320/11/194320/11/194320/11/194320/07/197517/05/195517/05/195517/05/195503/01/195503/01/195503/01/195513/03/196013/03/196026/11/196210/03/196424/06/196719/08/196919/08/196914/04/197003/02/196903/02/196929/09/198129/09/198129/09/198119/04/196319/04/196319/04/196304/10/198504/10/198503/06/197229/12/197401/05/196101/05/196101/05/196127/07/198003/11/196901/05/195812/03/194120/03/195716/01/194016/01/194016/01/194023/11/198705/07/195605/07/195605/07/195604/07/195704/07/195707/08/195907/08/195907/08/195901/03/196815/12/196326/04/196826/04/196826/04/196826/04/196805/06/196925/12/197125/12/197121/02/197407/11/196107/11/196127/03/195327/03/195327/03/195330/08/197230/08/197229/01/198114/06/197005/09/195105/09/195105/09/195106/01/195206/01/195206/01/195208/01/196908/01/196908/01/196908/01/196908/01/196908/01/196912/03/195912/03/195912/03/195904/02/196314/01/196414/01/196408/08/196308/08/196312/07/196808/10/195218/04/199723/12/196823/12/196816/08/198216/08/198218/06/198603/08/198103/08/198112/01/194612/01/194612/01/194612/01/194612/01/194627/05/194727/05/194727/05/194709/12/194909/12/194909/12/194909/12/194909/12/194909/12/194914/03/195214/03/195214/03/195219/10/195317/03/196017/03/196017/03/196017/03/196017/03/196010/10/196006/04/196507/11/198507/11/198507/11/198501/05/198503/01/198003/01/198003/01/198021/05/197121/05/197121/05/197105/09/196014/01/196808/08/196306/04/197206/04/197229/04/194429/04/194401/07/194330/04/194130/04/194130/04/194131/03/197231/03/197209/06/198401/12/194901/12/194901/12/194901/12/194901/06/199101/06/199101/06/199111/11/195211/11/195201/10/195201/10/195201/10/195223/07/195523/07/195507/12/195507/12/195501/04/195601/04/195601/04/195622/06/195718/07/195718/07/195718/07/195718/07/195725/01/195825/01/195825/01/195822/01/195906/08/195906/08/195901/12/195722/04/196022/04/196022/04/196009/03/196009/03/196027/06/196302/07/196302/07/196327/02/196426/02/196526/02/196526/02/196526/02/196511/05/199411/05/199425/05/199625/05/199617/11/196817/11/196817/11/196823/06/196801/12/196901/12/196901/12/196913/12/196814/03/196807/12/196915/01/196921/05/196921/05/196902/07/197102/07/197110/01/197229/02/197229/02/197205/03/197414/03/197614/03/197628/11/197608/03/197508/03/197515/12/197709/03/197709/03/197703/06/197703/06/197714/08/197514/08/197505/04/198505/04/198508/10/198622/05/198502/09/197602/09/197602/09/197618/08/198118/08/198114/04/194014/04/194029/08/198029/08/198029/08/198002/09/195820/10/195620/10/195620/10/195601/01/198001/01/198029/06/198229/06/198229/06/198211/07/194311/07/194320/07/196020/07/196020/07/196007/06/196307/06/196305/01/197323/04/195423/04/195425/10/197025/10/197026/01/197327/05/198019/06/194119/06/194119/06/194119/10/194201/07/194001/07/194003/09/194003/09/194003/09/194003/09/194003/09/194003/09/194025/06/194315/09/194215/09/194215/09/194223/03/194123/03/194123/03/194116/01/194216/01/194216/01/194228/01/194330/12/194030/12/194030/12/194014/02/194114/02/194101/04/194101/04/194101/04/194101/07/194601/07/194616/03/194120/05/194417/10/194317/10/194317/10/194324/06/194024/06/194024/06/194006/10/194206/10/194224/11/194324/11/194328/06/194128/06/194128/06/194104/11/197704/11/197706/06/194316/05/194316/05/194316/05/194304/11/194304/11/194328/01/194428/01/194420/11/197701/01/194312/10/194512/10/194512/10/194516/07/194416/07/194416/07/194430/08/194430/08/194430/08/194430/08/194426/01/194226/01/194226/01/194204/05/194404/05/194404/05/194429/06/194429/06/194416/03/194616/03/194620/05/194620/05/194631/03/194431/03/194431/03/194431/03/194431/03/194431/03/194431/03/194415/03/194215/03/194215/03/194219/05/197419/05/197419/05/197424/02/194124/02/194124/02/194129/03/194029/03/194029/03/194017/08/194217/08/194217/08/194212/05/194212/05/194212/05/194226/04/194126/04/194117/01/194326/04/194505/12/194405/12/194405/12/194427/06/194527/06/194527/06/194523/05/194023/05/194001/09/194401/09/194401/09/194418/10/194318/10/194318/10/194318/10/194518/10/194518/10/194527/12/194227/12/194227/12/194227/12/194227/12/194227/12/194214/01/194526/08/194426/08/194426/08/194411/03/194509/07/194509/07/194509/07/194517/12/194509/01/194809/01/194809/01/194808/04/194808/04/194808/04/194808/04/194827/07/194627/07/194605/12/194605/12/194605/12/194608/01/198012/02/194512/02/194512/02/194507/09/194106/06/198406/06/198406/06/198403/10/197223/08/198123/08/198123/08/198120/05/194923/05/194023/05/194017/05/194817/05/194817/05/194810/10/194810/10/194810/10/194805/02/195005/02/195008/01/194808/01/194803/08/194920/08/194923/04/194923/04/194923/04/194904/03/194804/03/194804/03/194814/04/194915/11/194915/11/194901/12/194701/12/194716/07/194914/09/194722/11/195022/11/195022/11/195024/11/194924/11/194930/04/195030/04/195030/04/195003/08/195003/08/195003/08/195010/02/195110/02/195110/02/195110/02/195110/02/195123/04/195126/11/195026/11/195026/11/195003/02/198803/02/198803/02/198830/05/194905/08/195224/12/194924/12/194924/12/194922/12/195007/08/195107/08/195107/08/195114/07/195114/07/195114/07/195106/02/198814/06/195214/06/195203/05/194906/05/195206/05/195206/05/195218/08/195218/08/195218/08/195218/08/195218/08/195218/08/195205/04/195105/04/195105/04/195115/04/195226/01/195426/01/195401/12/195201/12/195201/12/195211/04/195411/04/195411/04/195410/07/195310/07/195321/06/195421/06/195421/06/195415/11/195015/11/195015/11/195009/10/195209/10/195209/10/195207/08/195307/08/195306/03/195206/03/195201/04/195322/01/195416/06/195216/06/195216/06/195225/12/195325/12/195325/12/195301/05/198101/05/198128/08/195428/08/195428/08/195415/08/195215/08/195228/03/195104/09/195304/09/195304/09/195330/04/195430/04/195430/04/195430/01/195202/05/195405/11/195405/11/195405/11/195426/04/195426/04/195426/04/195426/04/195426/04/195426/04/195401/06/196022/05/195422/05/195417/03/195217/03/195217/10/197617/10/197604/02/195404/02/195404/02/195405/02/195514/06/195514/06/195510/03/195421/01/195403/11/195403/11/195414/03/198414/03/198414/03/198420/07/195703/09/195503/09/195505/11/195505/11/195520/05/195420/05/195414/06/195314/06/195314/06/195301/05/195601/05/195601/05/195610/02/195616/08/195316/08/195316/08/195326/12/195226/12/195226/12/195208/10/195708/10/195708/10/195707/06/195621/07/195421/07/195426/05/198426/05/198426/05/198408/09/195608/09/195610/06/195510/06/195510/06/195517/10/195804/08/195714/09/195414/09/195414/09/195415/02/195715/02/195714/02/195814/02/195807/01/195907/01/195907/01/195907/01/195904/12/195604/12/195613/07/194013/07/194013/07/194012/12/195612/12/195611/02/195611/02/195611/02/195605/10/195605/10/195605/10/195602/08/195902/08/195927/01/195627/01/195627/01/195625/01/196325/01/196315/08/195715/08/195715/08/195715/08/195715/08/195715/08/195715/08/195701/12/195701/12/195720/09/195720/09/195723/08/195718/11/198718/11/198724/06/195624/06/195624/06/195601/04/195918/12/195718/12/195715/11/195715/11/195715/11/195701/02/195801/02/195822/07/195722/07/195722/07/195718/01/195718/01/195718/01/195702/09/195702/09/195711/07/195711/07/195711/07/195719/07/195019/07/195019/07/195023/09/198315/02/195815/02/195806/06/195806/06/195806/06/195801/12/195301/12/195301/12/195309/10/195809/10/195809/10/195822/09/195722/09/195722/09/195702/09/195602/09/195602/09/195621/09/195821/09/195808/01/195908/01/195919/11/195817/10/195917/10/195906/12/195706/12/195706/12/195710/02/195910/02/195910/02/195910/02/195905/03/195805/03/195802/07/196002/07/196002/07/196002/07/196005/01/196005/01/196005/01/196016/12/195701/11/195906/07/196006/07/196006/07/196006/07/196006/07/196028/11/195826/04/196002/08/195702/08/195702/08/195712/06/197012/06/197012/06/197004/01/196104/01/196104/01/196107/06/196007/06/196005/01/195605/01/195602/02/196102/02/196102/02/196109/02/196009/02/196009/02/196016/08/195916/08/195924/05/196024/05/196024/05/196024/05/196002/10/196002/10/196002/10/196021/06/196021/06/196014/04/195914/05/195914/05/195914/05/195916/04/195316/04/195316/04/195307/01/196007/01/196007/01/196026/10/195826/10/195826/10/195816/01/196016/01/196013/04/195713/04/195717/08/196117/08/196117/08/196123/01/195823/01/195823/01/195803/12/196214/03/196114/03/196124/11/196124/11/196124/11/196103/04/196003/04/196003/04/196003/04/196003/04/196003/04/196016/09/196016/09/196016/09/196030/09/195930/09/195928/02/196108/01/196010/03/195910/03/195922/11/196022/11/196022/11/196001/09/195901/09/195901/09/195920/02/195920/02/195920/02/195930/11/195930/11/195930/11/195906/09/195806/09/195819/07/196019/07/196019/07/196019/07/196019/07/196001/06/196001/06/196026/02/196126/02/196121/04/196121/04/196121/04/196105/09/196005/09/196018/12/196118/12/196106/07/196106/07/196116/04/194821/07/196021/07/196021/07/196023/06/195823/06/195803/12/196108/07/196108/07/196113/06/196013/06/196003/01/196027/01/195927/01/195927/01/195921/01/196215/03/196225/09/196225/09/196225/09/196230/10/196030/10/196030/10/196008/04/196208/04/196208/04/196218/07/196018/07/196017/02/199517/02/199531/01/196131/01/196110/01/196310/01/196301/10/196101/10/196116/08/196616/08/196616/08/196616/08/196616/08/196618/09/196118/09/196123/05/196223/05/196223/05/196228/03/196228/03/196207/08/196107/08/196111/12/196011/12/196010/04/195925/09/196225/09/196210/08/196110/08/196105/01/196305/01/196305/01/196304/03/196304/03/196320/09/196120/09/196120/09/196117/12/198617/12/198617/12/198612/10/196110/10/196125/02/196413/12/196216/07/196216/07/196227/10/196127/10/196127/10/196116/06/196220/02/196220/02/196220/02/196204/06/196104/06/196131/08/196231/08/196231/08/196226/04/196327/03/196327/03/196301/09/196201/09/196201/09/196220/07/196220/07/196220/07/196220/07/196220/07/196219/02/196105/10/196224/02/196124/02/196110/04/196210/04/196210/04/196210/04/196210/04/196207/12/196107/12/196107/12/196117/09/196417/09/196417/09/196417/09/196417/09/196417/09/196417/09/196417/09/196417/09/196416/01/196218/06/196315/10/196208/09/196308/09/196308/09/196322/11/196322/11/196315/02/196415/02/196430/10/196318/06/196418/06/196418/06/196414/07/196214/07/196214/07/196204/12/196005/05/196505/07/196308/10/196308/10/196308/10/196308/10/196325/08/196425/08/196425/08/196402/07/196402/07/196425/11/196425/11/196425/11/196425/11/196410/10/196310/10/196316/08/196416/08/196430/12/196330/12/196330/12/196308/05/196301/11/199030/06/196430/06/196419/02/196310/03/196410/03/196410/03/196410/03/196410/03/196410/03/196410/03/196410/03/196410/03/196422/10/196422/10/196422/10/196404/06/196104/06/196104/06/196101/04/196201/04/196201/04/196211/07/196411/07/196402/07/196202/07/196202/07/196203/03/196403/03/196425/10/196410/02/196310/02/196310/02/196313/02/196328/11/196226/04/196526/04/196526/04/196531/01/196331/01/196331/01/196312/12/196312/12/196312/12/196310/08/196421/03/196421/03/196410/04/196511/01/196211/01/196211/01/196229/06/196523/01/196423/01/196423/01/196422/09/196422/09/196401/09/196401/09/196401/09/196401/09/196401/09/196407/02/196307/02/196307/02/196303/10/196303/10/196303/10/196303/10/196303/10/196303/10/196303/10/196303/10/196330/03/196530/03/196530/03/196501/08/196523/09/196510/10/196701/01/196501/01/196529/03/196404/08/196604/08/196601/01/196301/01/196301/01/196303/11/196503/11/196503/11/196526/04/196626/04/196626/04/196616/05/196416/05/196416/05/196402/07/196502/07/196502/07/196502/07/196502/07/196502/07/196502/07/196502/07/196531/03/196618/11/196402/08/195502/08/195502/08/195510/09/195310/09/195328/05/195728/05/195728/05/195711/03/197811/03/197811/03/197807/06/195607/06/195607/06/195612/11/195512/11/195512/11/195512/11/195516/10/195816/10/195816/10/195810/02/196627/07/196927/07/196927/07/196915/11/196503/01/194713/08/196813/08/196808/03/197208/03/197208/03/197222/12/198522/12/198518/11/196618/11/196618/11/196618/11/196630/03/195222/05/194822/05/194822/05/194816/02/195816/02/195816/02/195810/11/195730/01/195930/01/195930/01/195930/01/195925/12/196225/12/196225/12/196209/05/196309/05/196309/05/196317/05/196629/10/196629/10/196629/03/196829/03/196829/03/196805/04/198105/04/198125/04/196805/03/196811/11/196911/11/196911/11/196921/03/196421/03/196421/03/196421/03/196426/07/197905/08/198705/08/198705/08/198716/03/197601/10/194801/10/194801/10/194814/01/194514/01/194513/10/194301/02/194315/12/197915/12/197915/12/197901/05/195229/03/195216/06/195016/06/195016/06/195016/07/195316/07/195316/07/195302/05/195402/05/195428/06/195522/07/195722/07/195722/07/195707/01/196107/01/196108/12/196013/11/196129/01/196127/02/196320/12/196720/12/196726/03/196626/03/196626/03/196631/07/196831/07/196831/07/196801/09/197014/09/196925/01/197125/01/197125/01/197128/05/197028/05/197012/04/197118/02/197418/02/197407/08/197607/08/197615/03/198115/03/198115/03/198111/06/198411/06/198411/06/198409/06/198814/11/196108/06/194708/06/194708/06/194708/06/194717/08/194717/08/194730/12/194830/12/194830/12/194802/02/195512/10/195612/10/195612/10/195619/02/195819/02/195819/02/195820/05/195920/05/195920/05/195920/07/195825/03/196625/03/196625/03/196625/03/196612/12/196912/12/196926/05/197126/05/197103/12/197403/12/197403/12/197401/10/196501/10/196501/10/196528/05/195128/05/195128/05/195124/11/198224/11/198201/05/194501/05/194501/05/194518/08/196816/10/194216/10/194216/10/194221/02/194121/02/194121/02/194119/03/194019/03/194019/03/194021/10/196921/10/196921/10/196901/01/194523/12/194523/12/194523/12/194515/12/194220/10/194401/03/194501/03/194501/03/194501/08/194801/08/194801/08/194812/02/194912/02/194912/02/194911/06/194911/06/194911/06/194911/06/194910/06/197510/06/197525/06/195025/06/195025/06/195010/11/195010/11/195010/11/195012/04/195212/04/195212/04/195217/05/195217/05/195227/01/198027/01/198009/03/195309/03/195309/03/195309/03/195309/03/195306/09/198021/06/195621/06/195605/09/195605/09/195605/09/195605/09/195605/09/195602/10/195902/10/195922/02/195929/11/199129/11/199128/09/196028/09/196028/09/196024/12/196024/12/196025/04/196125/04/196125/04/196106/08/196106/08/196106/08/196116/03/196316/03/196316/03/196320/03/196320/03/196306/01/196006/01/196001/04/196301/04/196301/04/196301/04/196301/04/196315/01/196415/01/196415/02/196206/06/196409/07/196113/06/199718/09/196718/09/196718/09/196703/09/196803/09/196820/07/198620/07/198629/12/197029/12/197027/01/197130/11/197430/11/197409/12/197629/01/198127/03/198227/03/198227/03/198204/09/198406/05/198306/05/198306/05/198306/05/198315/05/198515/05/198515/05/198515/05/198515/05/198502/09/198101/10/197001/10/197001/08/197428/11/197828/11/197828/11/197828/11/197829/11/197414/02/196301/01/194801/01/194803/05/197703/05/197705/11/195001/01/195501/01/195501/01/195527/08/195310/03/196305/03/196609/11/197412/03/196712/03/196712/03/196721/06/196901/01/197413/01/194401/11/195001/11/195001/11/195009/02/194802/05/194602/05/194602/05/194602/05/194602/05/194602/05/194602/05/194602/05/194602/05/194610/01/195410/01/195418/10/195518/10/195518/10/195518/10/195518/10/195518/10/195506/07/195406/07/195406/07/195413/06/195513/06/195513/06/195520/12/197520/12/197515/04/197215/04/197205/05/196630/06/194730/06/194730/06/194727/10/196327/10/196327/10/196329/10/197129/10/197129/10/197106/12/195306/12/195306/12/195325/11/197625/11/197625/11/197630/10/198701/09/198525/03/198731/10/198731/10/198712/03/198708/10/199108/10/199108/10/199109/03/199122/09/199019/08/199106/12/197421/04/198621/04/198621/04/198605/04/198622/12/198822/12/198822/12/198819/12/198701/03/198804/08/198804/08/198823/06/198724/09/198124/09/198124/02/198724/02/198722/10/198822/10/198822/10/198812/06/198622/11/198022/11/198002/07/198802/07/198802/07/198811/12/199022/09/199409/12/198909/12/198909/12/198909/12/198909/12/198925/11/199023/07/198821/09/199021/09/199021/09/199021/07/195821/07/195821/07/195830/03/199120/04/197320/04/197320/04/197325/03/194820/12/195120/12/195120/12/195130/12/198729/04/195529/04/195529/04/195513/06/194713/06/194713/06/194718/10/196518/10/196524/03/196424/03/196424/10/197131/05/197016/08/196716/08/196716/08/196716/08/196715/11/196421/02/196521/02/196515/03/196524/05/196524/05/196524/05/196512/01/196614/10/199528/11/196428/11/196422/07/196322/07/196301/11/196501/11/196501/11/196501/11/196501/11/196516/12/196516/12/196516/12/196502/01/196602/01/196602/01/196623/02/196623/02/196612/07/196612/07/196616/07/195911/06/196401/04/196422/02/196622/02/196606/11/198506/11/198523/11/196523/11/196523/11/196517/07/196617/07/196609/01/196622/02/196622/02/196611/06/196611/06/196611/06/196602/06/196701/07/196401/07/196421/04/196621/04/196621/04/196623/11/196523/11/196523/11/196521/03/196714/05/196714/05/196714/05/196730/09/196309/11/196509/11/196529/07/196829/07/196808/08/196908/08/196908/08/196915/09/196615/09/196615/09/196615/09/196622/09/196622/09/196622/09/196622/09/196622/09/196616/02/196716/02/196716/02/196716/02/196721/02/196821/02/196821/02/196812/03/196823/09/196530/03/196608/08/196708/08/196705/06/196605/06/196612/07/196712/07/196712/07/196721/08/199501/03/196

In [ ]:
# I will drop the date eliments as for this process, it will likely
df_motor.drop(
    columns=['ID','Date_start_contract', 'Date_last_renewal', 'Date_next_renewal',
       'Date_birth', 'Date_driving_licence', 'Date_lapse', 'Cost_claims_year'])

In [ ]:
# The first step here we should likely choose to select Length as the missing variable of interest, then work to see if we can predict that missingness based upon the others then iterate.
Mo = df_motor[['ID','Seniority','Policies_in_force']].mean()

np.float64(4.252007487450906)

### Here we will make a database using postgreSQL

We've downloaded the stuff and installed it idk what's happening now after that tho, we should figure that out and make the database work

In [31]:
# connection to db

#load_dotenv() # Loads the env file which holds the password to the postgres database

#pgcon = psycopg2.connect(host = config['postgres']['host'],
#                         user = f"{config['postgres']['username']}", # accesses the username of the current user
#                         password = os.getenv("POSTGRES_PASSWORD"), # grabs the password from the env file
#                         database = config['postgres']['database_type'])